version: "3"
services:
  frontend:
    image: front-image:latest
    environment:
      - VITE_API_URL=http://localhost:8081
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8082:8082
  backend:
    image: back-image:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8081:8081
